version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: "daily"
    time: "20:00"
  ignore:
    - dependency-name: "google.golang.org/api"
    - dependency-name: "cloud.google.com/go/*"
- package-ecosystem: gomod
  directory: "/"
  target-branch: main
  schedule:
    interval: "weekly"
    day: "saturday"
- package-ecosystem: "maven"
  directory: "/acceptance-tests/apps/springstorageapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
  allow:
    - dependency-type: "all"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  reject:
    - "rc"      
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/mysqlapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/postgresqlapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/storageapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "00:00"
