version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: "daily"
    time: "20:00"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/dataprocapp"
  schedule:
    interval: "daily"
    time: "20:30"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/mysqlapp"
  schedule:
    interval: "daily"
    time: "21:00"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/postgresqlapp"
  schedule:
    interval: "daily"
    time: "21:30"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/redisapp"
  schedule:
    interval: "daily"
    time: "22:00"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/spannerapp"
  schedule:
    interval: "daily"
    time: "22:30"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/storageapp"
  schedule:
    interval: "daily"
    time: "23:00"
- package-ecosystem: npm
  directory: "/acceptance-tests/apps/stackdrivertraceapp"
  schedule:
    interval: "daily"
    time: "23:30"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "00:00"