version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: "daily"
    time: "20:00"
  ignore:
    - dependency-name: "google.golang.org/api"
    - dependency-name: "cloud.google.com/go/*"
- package-ecosystem: gomod
  directory: "/"
  target-branch: main
  schedule:
    interval: "weekly"
    day: "saturday"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/dataprocapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/mysqlapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/postgresqlapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/redisapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/spannerapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/storageapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/pubsubapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
- package-ecosystem: npm
  directory: "/acceptance-tests/apps/stackdrivertraceapp"
  schedule:
    interval: "weekly"
    day: "saturday"
  labels:
    - "test-dependencies"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "00:00"